#bridge-file-version: #144
##nu - ingame
execute if score game_active game_active matches 1 run execute as @a[tag=team_nu] run /titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"      Points to Win: "},{"score":{"name":"max_wins","objective":"max_wins"}},{"text":"      "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nTeam: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=baby] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=rocketjump] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=prism] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=removed_abilities] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=remote] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_nu,tag=vel_cancel] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
 
##lambda - ingame
execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda] run /titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"      Points to Win: "},{"score":{"name":"max_wins","objective":"max_wins"}},{"text":"      "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nTeam: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=baby] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=rocketjump] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=prism] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=removed_abilities] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=remote] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
#execute if score game_active game_active matches 1 run execute as @a[tag=team_lambda,tag=vel_cancel] run titleraw @s title {"rawtext":[{"text":"Scoreboard\n "},{"score":{"name":"team_nu","objective":"team_wins"}},{"text":"                             "},{"text":" "},{"score":{"name":"team_lambda","objective":"team_wins"}},{"text":"\n\nLives: "},{"score":{"name":"@s","objective":"lives"}},{"text":"     Ability: "},{"text":"     Team: "}]}
 
##No match active
execute if score game_active game_active matches 0 run execute as @a[tag=team_nu] run titleraw @s title {"rawtext":[{"text":"Scoreboard\nNo matches are active. "},{"text":"\n\nTeam: "}]}
execute if score game_active game_active matches 0 run execute as @a[tag=team_lambda] run titleraw @s title {"rawtext":[{"text":"Scoreboard\nNo matches are active. "},{"text":"\n\nTeam: "}]}
execute if score game_active game_active matches 0 run execute as @a[tag=!team_nu,tag=!team_lambda] run titleraw @s title {"rawtext":[{"text":"Scoreboard\nNo matches are active. "},{"text":"\n\nNo Team"}]}
 
execute as @a run execute if score round_active round_active matches 1 run execute if score time_elap_sec_ingame time_elap_sec_ingame matches 0..9 run execute as @s[tag=ingame] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nRemaining Players:\n"},{"score":{"name":"team_nu","objective":"player_alive_count"}},{"text":" - "},{"score":{"name":"team_lambda","objective":"player_alive_count"}},{"text":"\n\nLives:\n"},{"score":{"name":"@s","objective":"lives"}},{"text":"\n\nElapsed Time:\n"},{"score":{"name":"time_elap_min_ingame","objective":"time_elap_min_ingame"}},{"text":":0"},{"score":{"name":"time_elap_sec_ingame","objective":"time_elap_sec_ingame"}}]}
execute as @a run execute if score round_active round_active matches 1 run execute if score time_elap_sec_ingame time_elap_sec_ingame matches 10.. run execute as @s[tag=ingame] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nRemaining Players:\n"},{"score":{"name":"team_nu","objective":"player_alive_count"}},{"text":" - "},{"score":{"name":"team_lambda","objective":"player_alive_count"}},{"text":"\n\nLives:\n"},{"score":{"name":"@s","objective":"lives"}},{"text":"\n\nElapsed Time:\n"},{"score":{"name":"time_elap_min_ingame","objective":"time_elap_min_ingame"}},{"text":":"},{"score":{"name":"time_elap_sec_ingame","objective":"time_elap_sec_ingame"}}]}
 
 
###Loadout Stats
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
###########
 
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nPrism Recovery "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nBaby Storm "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nVelocity Cancel "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
 
######
 
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
scoreboard players add @a player_wins 0
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_marque] run titleraw @s actionbar {"rawtext":[{"text":"Marque's Weapons\n\nUnlocked Weapons:\n"},{"score":{"name":"count","objective":"weapon_unlock_count"}},{"text":"/23\n\nUnlocked Abilities:\n"},{"score":{"name":"count","objective":"ability_unlock_count"}},{"text":"/6"},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_splendid] run titleraw @s actionbar {"rawtext":[{"text":"Splendid Suits\n\nUnlocked Skins:\n"},{"score":{"name":"@s","objective":"skin_unlock_count"}},{"text":"/48\n\nUnlocked Effects:\n"},{"score":{"name":"coming_soon","objective":"ability_unlock_count"}},{"text":"Coming Soon"},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute if score round_active round_active matches 0 run execute if score cycle_stat_menus cycle_stat_menus matches 3 run scoreboard players set cycle_stat_menus cycle_stat_menus 0
 

execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 

##baby storm: 
##rocket jump: 
##antigrav prism: 
##no ability: 
##remote trigger: 
##vel cancel: 