#bridge-file-version: #1
scoreboard players add 0025_tundra enabled_arenas 0
scoreboard players add 0026_aether enabled_arenas 0
scoreboard players add 0028_plus enabled_arenas 0
scoreboard players add 0030_end enabled_arenas 0
scoreboard players add 0031_circus enabled_arenas 0
scoreboard players add 0032_beehive enabled_arenas 0
scoreboard players add 0033_dark_forest enabled_arenas 0
scoreboard players add 0034_digiglobe enabled_arenas 0
scoreboard players add 0037_crystal_cave enabled_arenas 0
scoreboard players add 0038_pendual enabled_arenas 0
scoreboard players add 0040_murkopolis enabled_arenas 0
scoreboard players add 0041_aquatica enabled_arenas 0
scoreboard players add 0042_conflict enabled_arenas 0
scoreboard players add 0043_shaparium enabled_arenas 0
scoreboard players add 0044_kyoto enabled_arenas 0
scoreboard players add 0045_overlord enabled_arenas 0
scoreboard players add 0050_shadow_forest enabled_arenas 0
scoreboard players add 0051_magic_forest enabled_arenas 0
scoreboard players add 0057_abstract_cyber enabled_arenas 0
scoreboard players add 0058_mikes_way enabled_arenas 0
scoreboard players add 0059_highway enabled_arenas 0
scoreboard players add 0060_cheeseburger enabled_arenas 0
scoreboard players add 0061_amethyst_domain enabled_arenas 0
scoreboard players add 0062_race_track enabled_arenas 0
scoreboard players add 0063_gob_dimension enabled_arenas 0
scoreboard players add 0064_playground enabled_arenas 0
scoreboard players add 0065_jurassic enabled_arenas 0
scoreboard players add 0066_egypt enabled_arenas 0
scoreboard players add 0067_cyberspace enabled_arenas 0
scoreboard players add 0068_fire_and_ice enabled_arenas 0
scoreboard players add 0069_shrek_on_crack enabled_arenas 0
scoreboard players add 0070_vaporwave enabled_arenas 0
scoreboard players add 0071_chess enabled_arenas 0
scoreboard players add 0073_deep_dark enabled_arenas 0
scoreboard players add 0074_demolition_derby enabled_arenas 0
scoreboard players add 0075_bananaland_bouncehouse enabled_arenas 0
scoreboard players add 0076_obstacle_course enabled_arenas 0
scoreboard players add 0077_flesh_prison enabled_arenas 0
scoreboard players add 0078_mcryes enabled_arenas 0
scoreboard players add 0079_slot_machine enabled_arenas 0
scoreboard players add 0080_pondwater enabled_arenas 0
scoreboard players add 0081_mole_life enabled_arenas 0
scoreboard players add 0082_big_warehouse enabled_arenas 0
scoreboard players add 0083_clash_royale enabled_arenas 0
scoreboard players add 0084_fruitiger_aero enabled_arenas 0
scoreboard players add 0085_amusement_park enabled_arenas 0
scoreboard players add 0086_arcade enabled_arenas 0
scoreboard players add 0087_cargo_deck enabled_arenas 0
scoreboard players add 0088_spleef enabled_arenas 0
scoreboard players add 0089_doomspire enabled_arenas 0
scoreboard players add 0090_candyland enabled_arenas 0
scoreboard players add 0091_ enabled_arenas 0
scoreboard players add 0092_ enabled_arenas 0
scoreboard players add 0093_ enabled_arenas 0
scoreboard players add 0094_ enabled_arenas 0
scoreboard players add 0095_ enabled_arenas 0
scoreboard players add 0096_ enabled_arenas 0
scoreboard players add 0097_ enabled_arenas 0
scoreboard players add 0098_ enabled_arenas 0
scoreboard players add 0105_ enabled_arenas 0