#bridge-file-version: #144

##PLEASE NOTE: SOME OF THIS FUNCTION HAS BEEN MOVED OVER TO THE SCRIPTING API JUST FOR EXTRA EFFICIENCY.

 





 
###Loadout Stats
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
 
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
execute if score train_timer_started train_timer_started matches 0 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Azure Stadium\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"new_pregame_timer_visual","objective":"new_pregame_timer_visual"}}]}
###########
 
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 1 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nNone "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 2 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRocket Jump "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 3 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nRemote Trigger "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 4 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nJudgement "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 5 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nBungee Anchor "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 0 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 1\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 1 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 2\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
execute if score train_timer_started train_timer_started matches 1 run execute as @a run execute if score round_active round_active matches 0 run /execute if score @s selected_ability matches 6 run /execute if score @s selected_loadout matches 2 run execute as @s[tag=teamed] run titleraw @s actionbar {"rawtext":[{"text":"Hog Railways\n\nSelected Loadout:\nLoadout 3\n\nSelected Ability:\nGround Slam "},{"text":"\n\nTime Remaining:\n"},{"score":{"name":"train_visual_timer","objective":"train_visual_timer"}}]}
 
 
######
 
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=1f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"1F-Metro\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=2f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"2F-Central Plaza\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=3f,tag=exit_stores] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"3F-Shopping Dist.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
scoreboard players add @a player_wins 0
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_marque] run titleraw @s actionbar {"rawtext":[{"text":"Marque's Weapons\n\nUnlocked Weapons:\n"},{"score":{"name":"count","objective":"weapon_unlock_count"}},{"text":"/23\n\nUnlocked Abilities:\n"},{"score":{"name":"count","objective":"ability_unlock_count"}},{"text":"/6"},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_gamblinzone] run titleraw @s actionbar {"rawtext":[{"text":"Gamblinzone\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nTokens:\n"},{"text":""},{"score":{"name":"@s","objective":"tokens"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_splendid] run titleraw @s actionbar {"rawtext":[{"text":"Splendid Suits\n\nUnlocked Skins:\n"},{"score":{"name":"@s","objective":"skin_unlock_count"}},{"text":"/48\n\nNext Reroll:\n"},{"score":{"name":"skin_reroll_timer","objective":"skin_reroll_timer"}},{"text":" Min."},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_questMaster] run titleraw @s actionbar {"rawtext":[{"text":"Rat of Wisdom\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nWisdom Earned:\n"},{"text":""},{"score":{"name":"@s","objective":"wisdom_earned"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute if score round_active round_active matches 0 run execute if score cycle_stat_menus cycle_stat_menus matches 3 run scoreboard players set cycle_stat_menus cycle_stat_menus 0
 

execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_reactor] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"REACTOR Settings\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits_new] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Credits\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits_new] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Credits\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits_new] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Credits\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits_new] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Credits\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_ueg] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"UEG Legacy Store\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_ueg] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"UEG Legacy Store\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_ueg] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"UEG Legacy Store\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_ueg] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"UEG Legacy Store\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_freedom] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Freedom B. Diner\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_freedom] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Freedom B. Diner\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_freedom] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Freedom B. Diner\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_freedom] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Freedom B. Diner\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_abilitystore] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"WIP Ability St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_abilitystore] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"WIP Ability St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_abilitystore] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"WIP Ability St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_abilitystore] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"WIP Ability St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_perfume_store] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"WIP Perfume St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_perfume_store] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"WIP Perfume St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_perfume_store] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"WIP Perfume St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_perfume_store] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"WIP Perfume St.\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_hot_topic_clone] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Hot Topic Clone\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_hot_topic_clone] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Hot Topic Clone\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_hot_topic_clone] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Hot Topic Clone\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_hot_topic_clone] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Hot Topic Clone\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_bank] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER Bank\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_bank] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER Bank\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_bank] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER Bank\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_bank] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER Bank\n\nGame Wins:\n"},{"score":{"name":"@s","objective":"player_wins"}},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_rpg] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"RPG Game Store\n\nNext Reroll:\n"},{"score":{"name":"skin_reroll_timer","objective":"skin_reroll_timer"}},{"text":" Min."},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_rpg] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"RPG Game Store\n\nNext Reroll:\n"},{"score":{"name":"skin_reroll_timer","objective":"skin_reroll_timer"}},{"text":" Min."},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_rpg] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"RPG Game Store\n\nNext Reroll:\n"},{"score":{"name":"skin_reroll_timer","objective":"skin_reroll_timer"}},{"text":" Min."},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_rpg] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"RPG Game Store\n\nNext Reroll:\n"},{"score":{"name":"skin_reroll_timer","objective":"skin_reroll_timer"}},{"text":" Min."},{"text":"\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_music] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"Torimoti Music\n\nUnlocked Music:\n"},{"score":{"name":"unlocked_music_count","objective":"unlocked_music_count"}},{"text":"/18\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
 
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 0..9 run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 0..9 run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":0"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_credits] run /execute if score @s time_elap_min matches 10.. run /execute if score @s time_elap_sec matches 10.. run titleraw @s actionbar {"rawtext":[{"text":"CYBER-S. Travel\n\nUnlocked Phases:\n"},{"score":{"name":"arenapacks_unlocked_count","objective":"arenapacks_unlocked_count"}},{"text":"/6\n\nPlay Time:\n"},{"score":{"name":"@s","objective":"time_elap_hr"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_min"}},{"text":":"},{"score":{"name":"@s","objective":"time_elap_sec"}},{"text":"\n\nCredits:\n"},{"score":{"name":"@s","objective":"credits"}},{"text":", "},{"score":{"name":"global_credits","objective":"global_credits"}},{"text":""}]}

execute as @a[tag=!ingame,tag=!teamed,tag=enter_riftzone] run titleraw @s actionbar {"rawtext":[{"text":"RIFT_ZONE\n\n§kFound Heads:§r§f\n"},{"score":{"name":"found_heads","objective":"found_heads"}}]}
execute as @a[tag=!ingame,tag=!teamed,tag=enter_j_mikes] run titleraw @s actionbar {"rawtext":[{"text":"JERSEY_MICHAELS\n\n"}]}
 

##Bungee Anchor: 
##rocket jump: 
##antigrav prism: 
##no ability: 
##remote trigger: 
##vel cancel: 