#bridge-file-version: #7
execute as @s positioned ~ ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
##
execute as @s positioned ~ ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
##
execute as @s positioned ~ ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~-1 ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~ ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air
execute as @s positioned ~1 ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:arenaborder_5 run execute as @s unless block ~ ~ ~ sm:arenaborder_4 run execute as @s unless block ~ ~ ~ sm:death_block run execute as @s unless block ~ ~ ~ sm:arenaborder run setblock ~ ~ ~ air