#bridge-file-version: #14
execute as @s positioned ~ ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~ ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~ ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~ ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
##
execute as @s positioned ~ ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
##
execute as @s positioned ~ ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~-1 ~-1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~-1 ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~ ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~-1 ~ run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
execute as @s positioned ~1 ~-1 ~1 run execute as @s unless block ~ ~ ~ air run execute as @s unless block ~ ~ ~ bedrock run execute as @s unless block ~ ~ ~ barrier run execute as @s unless block ~ ~ ~ deny run execute as @s unless block ~ ~ ~ allow run execute as @s unless block ~ ~ ~ sm:ceiling_bedrock run setblock ~ ~ ~ blue_ice
event entity @s sm:despawn
 