#bridge-file-version: #5
execute if score locker1_selectedthrusters locker1_selectedthrusters matches 1 run function select_recruit_thrusters
execute if score locker1_selectedthrusters locker1_selectedthrusters matches 2 run function select_sound_goddess_thrusters