#bridge-file-version: #6
execute as @a[tag=settings_info] run scoreboard players add @s settings_info_timer 1
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 10 run camera @s set minecraft:free ease 2 in_out_sine pos 114 16 14 facing 111 15 14
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 10 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fWelcome to the REACTOR Settings Center! To start, this is where you can change the movement and modifier settings!"}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 100 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fPress your interact key on the laptops to change the settings."}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 300 run camera @s set minecraft:free ease 2 in_out_sine pos 111 16 24 facing 109 15 26
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 300 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fThis area allows you to change settings relating to arenas!"}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 500 run camera @s set minecraft:free ease 2 in_out_sine pos 106 21 31 facing 106 21 32
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 500 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fThis area allows you to change access to different settings for the average player (if you are an operator)."}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 700 run camera @s set minecraft:free ease 2 in_out_sine pos 111 22 25 facing 114 21 27
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 700 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fFinally, this section is where you can select a preset to make the game instantly play like older versions, use similar rulesets to competitive play, etc."}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 900 run /tellraw @s {"rawtext":[{"text":"§e<Settings Robot> §fThat's all you need to know! Talk to the robot at the entrance if you need to see this again."}]}
execute as @a[tag=settings_info] run execute if score @s settings_info_timer matches 925 run function clear_settings_info